#page title
page_title                                :     Penedex                             # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1535416271                              # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :  https://testflight.apple.com/join/iQxlIZAu  # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Penedex                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The penultimate app to track and catalog your pens, inks, and daily carry combinations.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Connor Rose                                
your_link                                 : my-website                     
your_city                                 : Portland                                
email_address                             : hello@penedex.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : penedexapp
github_username                           : 
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Organize Your Collection
    description                           : Organize your pen and ink collections along with what combinations you are currently using.
    fontawesome_icon_name                 : pen-nib
    
  - title                                 : Dig Into the Details
    description                           : View details about your pens and inks such as brand, nib grind, ink color, and date purchased.
    fontawesome_icon_name                 : palette

  - title                                 : Statistics and History
    description                           : View statistics about your collection and keep a history of what you've inked up in the past.
    fontawesome_icon_name                 : chart-bar

  - title                                 : Homescreen Widgets
    description                           : Keep data about your collections available at a glance!
    fontawesome_icon_name                 : tint

  - title                                 : Filter your current carry
    description                           : Easily keep track of what pens are ready to use or need to be cleaned!
    fontawesome_icon_name                 : filter
  
  - title                                 : Themes and Icons
    description                           : Choose a look that works for you.
    fontawesome_icon_name                 : list

 # - title                                 : Smart App Banner
 #   description                           : Display a smart app banner on iOS devices.
  #  fontawesome_icon_name                 : arrow-alt-circle-down

 # - title                                 : Social Links
  #  description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
   # fontawesome_icon_name                 : link

 # - title                                 : FontAwesome Support
  #  description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
   # fontawesome_icon_name                 : info-circle

#  - title                                 : # New Feature Title
 #   description                           : # New Feature Description
  #  fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#ff9100"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#ff9100"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
